nmsbackend:
  build: container
  ports:
    - "80:80"
  volumes:
    - .:/var/www
  links:
    - database
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  ports:
    - "8080:80"
  environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=root
  links:
    - database:mysql
database:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=nmsfrance
    - MYSQL_USER=nmsfrance
    - MYSQL_PASSWORD=root
